name: Build Static Image in Coolify
on:
  push:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "DILab-Ivy/ivy-testing-ui"

jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3 #checks out the code from the repository
      - name: Login to ghcr.io #logs credentials to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN  }}
      - name: Build image and push to registry  #builds docker image in root and targets linux platform
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Deploy to Coolify #Set up webhook and coolify token properly 
        run: | 
         curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'


#TODO:
# Configure the Coolify webhook (COOLIFY_WEBHOOK) and token (COOLIFY_TOKEN) in your repository’s secrets.